### ISSUE TITLE
Error on Bot startup

### ISSUE THREAD

**Issue by rschaerer** [Liryna/FacebookBot#11]
I get the following error on bot Startup with `TELEGRAM_USER="[USERNAME]" APP_TOKEN="[TOKEN]" node facebookbot.js`:

````
/home/nosudo/telegram/FacebookBot/facebookbot.js:29
login({email: config.email, password: config.password}, async function (err, api) {
                                                        ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
````
Does anyone know what I'm doing wrong?

**Comment by Kreastr** [comment]
I guess you have this issue. 
https://stackoverflow.com/questions/46306997/syntaxerror-missing-after-argument-list-when-using-async

**Comment by rschaerer** [comment]
Thanks @Kreastr . I'll check this and tell you if this was the case. If yes, I'll issue a PR with extended dependencies (and fix the `###usage` markdown markup issue as well).

**Comment by rschaerer** [comment]
Hi @Kreastr , thanks for your guess! My old nodejs version really was the issue. :hugs:
