### ISSUE TITLE
Bot Crash When Replied To

### ISSUE THREAD

**Issue by ibrokemypie** [Liryna/FacebookBot#6]
```
info Got answer in  624
ERR! ERROR in listen -->  TypeError: Cannot read property 'length' of undefined
ERR! ERROR in listen -->      at callback (/Users/Conor/FacebookBot/facebookbot.js:149:36)
ERR! ERROR in listen -->      at parsePackets (/Users/Conor/FacebookBot/node_modules/facebook-chat-api/src/listen.js:161:22)
ERR! ERROR in listen -->      at Array.forEach (native)
ERR! ERROR in listen -->      at /Users/Conor/FacebookBot/node_modules/facebook-chat-api/src/listen.js:108:12
ERR! ERROR in listen -->      at tryCatcher (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/util.js:26:23)
ERR! ERROR in listen -->      at Promise._settlePromiseFromHandler (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:510:31)
ERR! ERROR in listen -->      at Promise._settlePromiseAt (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:584:18)
ERR! ERROR in listen -->      at Promise._settlePromises (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:700:14)
ERR! ERROR in listen -->      at Async._drainQueue (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:123:16)
ERR! ERROR in listen -->      at Async._drainQueues (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:133:10)
ERR! ERROR in listen -->      at Immediate.Async.drainQueues (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:15:14)
ERR! ERROR in listen -->      at runCallback (timers.js:570:20)
ERR! ERROR in listen -->      at tryOnImmediate (timers.js:550:5)
ERR! ERROR in listen -->      at processImmediate [as _immediateCallback] (timers.js:529:5)
ERR! ERROR in listen -->   TypeError: Cannot read property 'length' of undefined
ERR! ERROR in listen -->      at callback (/Users/Conor/FacebookBot/facebookbot.js:149:36)
ERR! ERROR in listen -->      at parsePackets (/Users/Conor/FacebookBot/node_modules/facebook-chat-api/src/listen.js:161:22)
ERR! ERROR in listen -->      at Array.forEach (native)
ERR! ERROR in listen -->      at /Users/Conor/FacebookBot/node_modules/facebook-chat-api/src/listen.js:108:12
ERR! ERROR in listen -->      at tryCatcher (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/util.js:26:23)
ERR! ERROR in listen -->      at Promise._settlePromiseFromHandler (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:510:31)
ERR! ERROR in listen -->      at Promise._settlePromiseAt (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:584:18)
ERR! ERROR in listen -->      at Promise._settlePromises (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:700:14)
ERR! ERROR in listen -->      at Async._drainQueue (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:123:16)
ERR! ERROR in listen -->      at Async._drainQueues (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:133:10)
ERR! ERROR in listen -->      at Immediate.Async.drainQueues (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:15:14)
ERR! ERROR in listen -->      at runCallback (timers.js:570:20)
ERR! ERROR in listen -->      at tryOnImmediate (timers.js:550:5)
ERR! ERROR in listen -->      at processImmediate [as _immediateCallback] (timers.js:529:5)
Unhandled rejection TypeError: Cannot read property 'senderName' of undefined
    at callback (/Users/Conor/FacebookBot/facebookbot.js:148:26)
    at /Users/Conor/FacebookBot/node_modules/facebook-chat-api/src/listen.js:218:9
    at tryCatcher (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

**Comment by Liryna** [comment]
Hello @ibrokemypie ,

Seems like `senderName` from https://github.com/Schmavery/facebook-chat-api is null for a reason.
Can you try to update dependancy ?

**Comment by ibrokemypie** [comment]
@Liryna 
downloaded the latest version of facebook-chat-api and stuck it in modules over the old one, same problem

```
info Got answer in  1803
ERR! ERROR in listen -->  TypeError: Cannot read property 'length' of undefined
ERR! ERROR in listen -->      at callback (/Users/Conor/FacebookBot/facebookbot.js:149:36)
ERR! ERROR in listen -->      at handleMessagingEvents (/Users/Conor/FacebookBot/node_modules/facebook-chat-api/src/listen.js:47:9)
ERR! ERROR in listen -->      at parsePackets (/Users/Conor/FacebookBot/node_modules/facebook-chat-api/src/listen.js:164:19)
ERR! ERROR in listen -->      at Array.forEach (native)
ERR! ERROR in listen -->      at /Users/Conor/FacebookBot/node_modules/facebook-chat-api/src/listen.js:108:12
ERR! ERROR in listen -->      at tryCatcher (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/util.js:26:23)
ERR! ERROR in listen -->      at Promise._settlePromiseFromHandler (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:510:31)
ERR! ERROR in listen -->      at Promise._settlePromiseAt (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:584:18)
ERR! ERROR in listen -->      at Promise._settlePromises (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:700:14)
ERR! ERROR in listen -->      at Async._drainQueue (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:123:16)
ERR! ERROR in listen -->      at Async._drainQueues (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:133:10)
ERR! ERROR in listen -->      at Immediate.Async.drainQueues (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:15:14)
ERR! ERROR in listen -->      at runCallback (timers.js:570:20)
ERR! ERROR in listen -->      at tryOnImmediate (timers.js:550:5)
ERR! ERROR in listen -->      at processImmediate [as _immediateCallback] (timers.js:529:5)
ERR! ERROR in listen -->   TypeError: Cannot read property 'length' of undefined
ERR! ERROR in listen -->      at callback (/Users/Conor/FacebookBot/facebookbot.js:149:36)
ERR! ERROR in listen -->      at handleMessagingEvents (/Users/Conor/FacebookBot/node_modules/facebook-chat-api/src/listen.js:47:9)
ERR! ERROR in listen -->      at parsePackets (/Users/Conor/FacebookBot/node_modules/facebook-chat-api/src/listen.js:164:19)
ERR! ERROR in listen -->      at Array.forEach (native)
ERR! ERROR in listen -->      at /Users/Conor/FacebookBot/node_modules/facebook-chat-api/src/listen.js:108:12
ERR! ERROR in listen -->      at tryCatcher (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/util.js:26:23)
ERR! ERROR in listen -->      at Promise._settlePromiseFromHandler (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:510:31)
ERR! ERROR in listen -->      at Promise._settlePromiseAt (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:584:18)
ERR! ERROR in listen -->      at Promise._settlePromises (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:700:14)
ERR! ERROR in listen -->      at Async._drainQueue (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:123:16)
ERR! ERROR in listen -->      at Async._drainQueues (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:133:10)
ERR! ERROR in listen -->      at Immediate.Async.drainQueues (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:15:14)
ERR! ERROR in listen -->      at runCallback (timers.js:570:20)
ERR! ERROR in listen -->      at tryOnImmediate (timers.js:550:5)
ERR! ERROR in listen -->      at processImmediate [as _immediateCallback] (timers.js:529:5)
Unhandled rejection TypeError: Cannot read property 'senderName' of undefined
    at callback (/Users/Conor/FacebookBot/facebookbot.js:148:26)
    at /Users/Conor/FacebookBot/node_modules/facebook-chat-api/src/listen.js:218:9
    at tryCatcher (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/Conor/FacebookBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

**Comment by Liryna** [comment]
@ibrokemypie I am not really using the bot anymore 😢 
I think this is probably not a big problem. Do you think you can look into it ?

**Comment by ibrokemypie** [comment]
@Liryna i can certainly try, however never used node before and have very little knowledge of js, so i guess we will see how far i get.
sending works, its just receiving that is broken and causes this error every time from any sender.
